---

image:
  repository: ghcr.io/ministryofjustice/hmpps-sharepoint-discovery
  tag: xxx
  
generic-prometheus-alerts:
  targetApplication: hmpps-sharepoint-discovery

discoveryCronJob:
  namespace_secrets:
    hmpps-sharepoint-discovery:
      SERVICE_CATALOGUE_API_ENDPOINT: "SERVICE_CATALOGUE_API_ENDPOINT"
      SERVICE_CATALOGUE_API_KEY: "SERVICE_CATALOGUE_API_KEY"
    azure-sharepoint-service-principal:
      AZ_TENANT_ID: "AZ_TENANT_ID"
      SP_CLIENT_ID: "SP_CLIENT_ID"
      SP_CLIENT_SECRET: "SP_CLIENT_SECRET"
      SP_SITE_ID: "SP_SITE_ID"
    hmpps-sre-app-slack-bot:
      SLACK_BOT_TOKEN: "SLACK_BOT_TOKEN"
