---
# Per environment values which override defaults in hmpps-sharepoint-discovery/values.yaml

generic-prometheus-alerts:
  alertSeverity: hmpps-sre-alerts-nonprod

discoveryCronJob:
  enabled: true
  sharepoint_discovery_schedule: "*/30 8-17 * * 1-5"
  env:
    LOG_LEVEL: info
  namespace_secrets:
    hmpps-envoy-https-proxy-env:
      HTTP_PROXY: "HTTP_PROXY"
      HTTPS_PROXY: "HTTPS_PROXY"
      NO_PROXY: "NO_PROXY"
      http_proxy: "HTTP_PROXY"
      https_proxy: "HTTPS_PROXY"
      no_proxy: "NO_PROXY"
